version: '3'
services:

  app:
    build: .
    ports:
      - "5432:5432"
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: batman
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: